In [1]:
import numpy as np
import pandas as pd

In [4]:
df1 = pd.read_csv('reporte_metricas_inventario/01_resumen_metricas.csv')
df2 = pd.read_csv('reporte_metricas_inventario/02_consumo_reconstruido_por_intervalo.csv')
df3 = pd.read_csv('reporte_metricas_inventario/03_consumo_diario_estimado.csv')
df4 = pd.read_csv('reporte_metricas_inventario/04_consumo_semanal.csv')
df5 = pd.read_csv('reporte_metricas_inventario/05_lead_times_detalle.csv')
df6 = pd.read_csv('reporte_metricas_inventario/06_compras_resumen.csv')
df7 = pd.read_csv('reporte_metricas_inventario/07_evaluacion_politica_5_dias.csv')
df8 = pd.read_csv('reporte_metricas_inventario/08_calidad_datos.csv')
df9 = pd.read_csv('reporte_metricas_inventario/09_metricas_rop.csv')

In [14]:
df1

,material,fecha_inicio_inventario,fecha_fin_inventario,observaciones_inventario,consumo_total_reconstruido,consumo_promedio_diario,desv_est_consumo_diario,consumo_semanal_promedio,desv_est_consumo_semanal,cv_semanal,...,desv_est_precio_historico,cv_precio_historico,valor_inventario_promedio_estimado,valor_inventario_actual_estimado,valor_inventario_maximo_estimado,stock_seguridad_95_ilustrativo,rop_95_ilustrativo,rop_95_con_lead_time_p90,intervalos_con_ajuste_no_conciliado,pct_intervalos_con_ajuste_no_conciliado
0,ALAMBRE RECOCIDO,2026-05-19,2026-08-11,71,4403.37,52.421071,102.874133,338.720769,265.241747,0.783069,...,2.387560,0.110631,23885.373617,4784.70000,48678.604200,541.793793,1079.109775,1733.647888,6,8.571429
1,ALAMBRON,2026-05-19,2026-08-11,71,5304.00,63.142857,176.710088,408.000000,485.067908,1.188892,...,1.960576,0.111661,21770.078873,8738.73000,49896.315000,605.115522,878.734570,1090.894648,5,7.142857
2,ARMEX DE 15 x 15,2026-05-19,2026-08-11,71,614.00,7.309524,9.512324,47.230769,19.984779,0.423130,...,12.028874,0.095475,40667.597324,2463.52000,84837.470000,64.517419,188.779324,365.634066,1,1.428571
3,ARMEX DE 15 x 20,2026-05-19,2026-08-11,71,1929.00,22.964286,65.314925,148.384615,150.953380,1.017312,...,10.875334,0.084191,23407.132394,9540.40000,79294.800000,354.317796,604.054403,1026.343569,6,8.571429
4,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",2026-05-19,2026-08-11,71,885.00,10.535714,25.413812,68.076923,85.495279,1.255863,...,10.326611,0.238726,7996.685915,4228.03500,15784.664000,112.842262,189.602466,277.855991,2,2.857143
5,"CLAVO PARA MADERA DE 2 1/2""",2026-05-19,2026-08-11,71,803.20,9.561905,25.675680,61.784615,72.457442,1.172742,...,0.156258,0.007038,4205.639067,1985.02040,9778.121276,100.542966,154.727093,178.680593,4,5.714286
6,"CLAVO PARA MADERA DE 4""",2026-05-19,2026-08-11,71,319.00,3.797619,16.449427,24.538462,41.660564,1.697766,...,0.136492,0.006136,5759.354963,3753.69588,8615.880680,58.035748,75.504796,94.580904,2,2.857143
7,MALLA ELECTROSOLDADA 6-6-10/10,2026-05-19,2026-08-11,71,10648.70,126.770238,160.821485,819.130769,393.787684,0.480738,...,2.662488,0.155872,37813.778085,36942.50000,130052.377000,831.339705,2083.195806,3812.191982,6,8.571429
8,"VARILLA CORRUGADA 1/2""",2026-05-19,2026-08-11,71,1501.00,17.869048,64.994214,115.461538,152.425971,1.320145,...,13.132883,0.063499,65281.710423,60341.76000,126131.040000,261.888377,369.102663,499.291600,4,5.714286
9,"VARILLA CORRUGADA 3/8""",2026-05-19,2026-08-11,71,3480.00,41.428571,92.262393,267.692308,232.944854,0.870196,...,7.472940,0.063255,73249.372958,51972.80000,187456.440000,344.185718,557.246943,691.550005,6,8.571429

In [15]:
df2

,material,fecha,inventario,fecha_anterior,inventario_anterior,dias_intervalo,recepciones_intervalo,consumo_intervalo,consumo_diario,ajuste_datos
0,ALAMBRE RECOCIDO,2026-05-19,1924.63,NaN,NaN,NaN,NaN,NaN,NaN,False
1,ALAMBRE RECOCIDO,2026-05-20,1924.63,2026-05-19,1924.63,1.0,0.0,0.0,0.0,False
2,ALAMBRE RECOCIDO,2026-05-21,1674.63,2026-05-20,1924.63,1.0,0.0,250.0,250.0,False
3,ALAMBRE RECOCIDO,2026-05-22,1674.63,2026-05-21,1674.63,1.0,0.0,0.0,0.0,False
4,ALAMBRE RECOCIDO,2026-05-23,1667.63,2026-05-22,1674.63,1.0,0.0,7.0,7.0,False
...,...,...,...,...,...,...,...,...,...,...
705,"VARILLA CORRUGADA 3/8""",2026-08-06,64.00,2026-08-05,161.00,1.0,0.0,97.0,97.0,False
706,"VARILLA CORRUGADA 3/8""",2026-08-07,34.00,2026-08-06,64.00,1.0,0.0,30.0,30.0,False
707,"VARILLA CORRUGADA 3/8""",2026-08-08,19.00,2026-08-07,34.00,1.0,0.0,15.0,15.0,False
708,"VARILLA CORRUGADA 3/8""",2026-08-10,469.00,2026-08-08,19.00,2.0,0.0,NaN,NaN,True
709,"VARILLA CORRUGADA 3/8""",2026-08-11,440.00,2026-08-10,469.00,1.0,0.0,29.0,29.0,False

In [7]:
df3.head()

           material       fecha  consumo_estimado_dia
0  ALAMBRE RECOCIDO  2026-05-20                   0.0
1  ALAMBRE RECOCIDO  2026-05-21                 250.0
2  ALAMBRE RECOCIDO  2026-05-22                   0.0
3  ALAMBRE RECOCIDO  2026-05-23                   7.0
4  ALAMBRE RECOCIDO  2026-05-24                  25.0

In [8]:
df4.head()

           material  iso_year  iso_week  consumo_semanal
0  ALAMBRE RECOCIDO      2026        21            282.0
1  ALAMBRE RECOCIDO      2026        22            995.0
2  ALAMBRE RECOCIDO      2026        23             90.0
3  ALAMBRE RECOCIDO      2026        24            658.0
4  ALAMBRE RECOCIDO      2026        25            385.0

In [9]:
df5.head()

,Material,Proveedor (Texto),ID de pedido de compra,PU Promedio,Cantidad,Valor facturado,pedido,recibido,dias en llegar,lead_time_calculado
0,ALAMBRE RECOCIDO,HOME DEPOT MEXICO S DE RL DE CV,40990,19.00,1500,28500,2026-01-07,2026-01-09,2,2
1,ALAMBRE RECOCIDO,HOME DEPOT MEXICO S DE RL DE CV,41394,19.85,1000,19850,2026-01-22,2026-03-10,47,47
2,ALAMBRE RECOCIDO,HOME DEPOT MEXICO S DE RL DE CV,41979,19.85,1500,29775,2026-02-16,2026-02-19,3,3
3,ALAMBRE RECOCIDO,HOME DEPOT MEXICO S DE RL DE CV,42976,20.39,1000,20390,2026-03-26,2026-04-02,7,7
4,ALAMBRE RECOCIDO,MEXLAM CONCEPTOS SA DE CV,43762,20.30,1500,30450,2026-04-17,2026-04-24,7,7

In [10]:
df6.head()

,Material,numero_pedidos,cantidad_total,cantidad_promedio,valor_total,valor_promedio,pu_promedio,lead_time_promedio,lead_time_mediana,lead_time_max
0,ALAMBRE RECOCIDO,8,9000,1125.000000,189975,23746.875000,21.581250,10.250000,6.0,47
1,ALAMBRON,6,6000,1000.000000,105350,17558.333333,17.558333,4.333333,4.5,7
2,ARMEX DE 15 x 15,5,1332,266.400000,168623,33724.600000,125.990000,17.000000,7.0,47
3,ARMEX DE 15 x 20,8,1967,245.875000,252061,31507.625000,129.175000,10.875000,6.0,47
4,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",7,1000,142.857143,43827,6261.000000,43.257143,7.285714,7.0,16

In [26]:
df7.groupby(df7['material']).head()

,material,fecha_evaluacion,consumo_7d_previos,promedio_diario_7d,pronostico_5d,consumo_real_5d,error,error_absoluto,subestima,sobreestima
0,ALAMBRE RECOCIDO,2026-05-27,809.0,115.571429,577.857143,468.00,109.857143,109.857143,False,True
1,ALAMBRE RECOCIDO,2026-05-28,809.0,115.571429,577.857143,468.00,109.857143,109.857143,False,True
2,ALAMBRE RECOCIDO,2026-05-29,578.0,82.571429,412.857143,465.00,-52.142857,52.142857,True,False
3,ALAMBRE RECOCIDO,2026-05-30,1023.0,146.142857,730.714286,21.00,709.714286,709.714286,False,True
4,ALAMBRE RECOCIDO,2026-05-31,1020.0,145.714286,728.571429,69.00,659.571429,659.571429,False,True
73,ALAMBRON,2026-05-27,1100.0,157.142857,785.714286,366.00,419.714286,419.714286,False,True
74,ALAMBRON,2026-05-28,1100.0,157.142857,785.714286,366.00,419.714286,419.714286,False,True
75,ALAMBRON,2026-05-29,1150.0,164.285714,821.428571,316.00,505.428571,505.428571,False,True
76,ALAMBRON,2026-05-30,1466.0,209.428571,1047.142857,100.00,947.142857,947.142857,False,True
77,ALAMBRON,2026-05-31,1466.0,209.428571,1047.142857,100.00,947.142857,947.142857,False,True
146,ARMEX DE 15 x 15,2026-05-27,19.0,2.714286,13.571429,51.50,-37.928571,37.928571,True,False
147,ARMEX DE 15 x 15,2026-05-28,48.0,6.857143,34.285714,23.00,11.285714,11.285714,False,True
148,ARMEX DE 15 x 15,2026-05-29,50.0,7.142857,35.714286,44.00,-8.285714,8.285714,True,False
149,ARMEX DE 15 x 15,2026-05-30,49.0,7.000000,35.000000,87.00,-52.000000,52.000000,True,False
150,ARMEX DE 15 x 15,2026-05-31,55.0,7.857143,39.285714,68.00,-28.714286,28.714286,True,False
219,ARMEX DE 15 x 20,2026-05-27,2.0,0.285714,1.428571,586.00,-584.571429,584.571429,True,False
220,ARMEX DE 15 x 20,2026-05-28,502.0,71.714286,358.571429,89.00,269.571429,269.571429,False,True
221,ARMEX DE 15 x 20,2026-05-29,502.0,71.714286,358.571429,130.00,228.571429,228.571429,False,True
222,ARMEX DE 15 x 20,2026-05-30,540.0,77.142857,385.714286,125.00,260.714286,260.714286,False,True
223,ARMEX DE 15 x 20,2026-05-31,583.0,83.285714,416.428571,103.00,313.428571,313.428571,False,True
292,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",2026-05-27,103.0,14.714286,73.571429,181.50,-107.928571,107.928571,True,False
293,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",2026-05-28,103.0,14.714286,73.571429,230.00,-156.428571,156.428571,True,False
294,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",2026-05-29,134.0,19.142857,95.714286,206.00,-110.285714,110.285714,True,False
295,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",2026-05-30,139.0,19.857143,99.285714,201.00,-101.714286,101.714286,True,False
296,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",2026-05-31,234.0,33.428571,167.142857,105.00,62.142857,62.142857,False,True
365,"CLAVO PARA MADERA DE 2 1/2""",2026-05-27,205.0,29.285714,146.428571,83.00,63.428571,63.428571,False,True
366,"CLAVO PARA MADERA DE 2 1/2""",2026-05-28,205.0,29.285714,146.428571,83.00,63.428571,63.428571,False,True
367,"CLAVO PARA MADERA DE 2 1/2""",2026-05-29,280.0,40.000000,200.000000,42.00,158.000000,158.000000,False,True
368,"CLAVO PARA MADERA DE 2 1/2""",2026-05-30,285.0,40.714286,203.571429,37.00,166.571429,166.571429,False,True
369,"CLAVO PARA MADERA DE 2 1/2""",2026-05-31,284.0,40.571429,202.857143,64.00,138.857143,138.857143,False,True
438,"CLAVO PARA MADERA DE 4""",2026-05-27,100.0,14.285714,71.428571,1.00,70.428571,70.428571,False,True
439,"CLAVO PARA MADERA DE 4""",2026-05-28,100.0,14.285714,71.428571,1.00,70.428571,70.428571,False,True
440,"CLAVO PARA MADERA DE 4""",2026-05-29,100.0,14.285714,71.428571,1.00,70.428571,70.428571,False,True
441,"CLAVO PARA MADERA DE 4""",2026-05-30,100.0,14.285714,71.428571,1.00,70.428571,70.428571,False,True
442,"CLAVO PARA MADERA DE 4""",2026-05-31,101.0,14.428571,72.142857,20.00,52.142857,52.142857,False,True
511,MALLA ELECTROSOLDADA 6-6-10/10,2026-05-27,753.0,107.571429,537.857143,1033.45,-495.592857,495.592857,True,False
512,MALLA ELECTROSOLDADA 6-6-10/10,2026-05-28,1006.0,143.714286,718.571429,792.90,-74.328571,74.328571,True,False
513,MALLA ELECTROSOLDADA 6-6-10/10,2026-05-29,468.0,66.857143,334.285714,792.90,-458.614286,458.614286,True,False
514,MALLA ELECTROSOLDADA 6-6-10/10,2026-05-30,725.0,103.571429,517.857143,772.90,-255.042857,255.042857,True,False
515,MALLA ELECTROSOLDADA 6-6-10/10,2026-05-31,1028.0,146.857143,734.285714,1072.90,-338.614286,338.614286,True,False
584,"VARILLA CORRUGADA 1/2""",2026-05-27,90.0,12.857143,64.285714,109.00,-44.714286,44.714286,True,False
585,"VARILLA CORRUGADA 1/2""",2026-05-28,94.0,13.428571,67.142857,107.00,-39.857143,39.857143,True,False
586,"VARILLA CORRUGADA 1/2""",2026-05-29,116.0,16.571429,82.857143,96.00,-13.142857,13.142857,True,False
587,"VARILLA CORRUGADA 1/2""",2026-05-30,140.0,20.000000,100.000000,72.00,28.000000,28.000000,False,True
588,"VARILLA CORRUGADA 1/2""",2026-05-31,191.0,27.285714,136.428571,21.00,115.428571,115.428571,False,True
657,"VARILLA CORRUGADA 3/8""",2026-05-27,956.0,136.571429,682.857143,238.00,444.857143,444.857143,False,True
658,"VARILLA CORRUGADA 3/8""",2026-05-28,929.0,132.714286,663.571429,240.00,423.571429,423.571429,False,True
659,"VARILLA CORRUGADA 3/8""",2026-05-29,917.0,131.000000,655.000000,271.00,384.000000,384.000000,False,True
660,"VARILLA CORRUGADA 3/8""",2026-05-30,987.0,141.000000,705.000000,141.00,564.000000,564.000000,False,True
661,"VARILLA CORRUGADA 3/8""",2026-05-31,1010.0,144.285714,721.428571,101.00,620.428571,620.428571,False,True

In [24]:
df7[df7['subestima'] == df7['sobreestima']]

,material,fecha_evaluacion,consumo_7d_previos,promedio_diario_7d,pronostico_5d,consumo_real_5d,error,error_absoluto,subestima,sobreestima
209,ARMEX DE 15 x 15,2026-07-29,49.0,7.0,35.0,35.0,0.0,0.0,False,False
460,"CLAVO PARA MADERA DE 4""",2026-06-18,0.0,0.0,0.0,0.0,0.0,0.0,False,False
503,"CLAVO PARA MADERA DE 4""",2026-07-31,0.0,0.0,0.0,0.0,0.0,0.0,False,False
504,"CLAVO PARA MADERA DE 4""",2026-08-01,0.0,0.0,0.0,0.0,0.0,0.0,False,False

In [12]:
df8.head()

,material,intervalos_analizados,intervalos_con_entrada_no_conciliada,pct_ajustes,pedidos_con_lt,pedidos_lt_inconsistente
0,ALAMBRE RECOCIDO,70,6,8.571429,8,0
1,ALAMBRON,70,5,7.142857,6,0
2,ARMEX DE 15 x 15,70,1,1.428571,5,0
3,ARMEX DE 15 x 20,70,6,8.571429,8,0
4,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",70,2,2.857143,7,0

In [13]:
df9.head()

,material,consumo_promedio_diario,desv_est_consumo_diario,lead_time_promedio_dias,lead_time_p90_dias,tiempo_administrativo_dias,reposicion_total_promedio_dias,reposicion_total_p90_dias,stock_seguridad_95_ilustrativo,rop_95_ilustrativo,rop_95_con_lead_time_p90
0,ALAMBRE RECOCIDO,52.421071,102.874133,10.250000,19.0,0.0,10.250000,19.0,541.793793,1079.109775,1733.647888
1,ALAMBRON,63.142857,176.710088,4.333333,6.0,0.0,4.333333,6.0,605.115522,878.734570,1090.894648
2,ARMEX DE 15 x 15,7.309524,9.512324,17.000000,37.0,0.0,17.000000,37.0,64.517419,188.779324,365.634066
3,ARMEX DE 15 x 20,22.964286,65.314925,10.875000,22.5,0.0,10.875000,22.5,354.317796,604.054403,1026.343569
4,"CLAVO P/CONCRETO 2 1/2"" GALV 1 KG",10.535714,25.413812,7.285714,12.4,0.0,7.285714,12.4,112.842262,189.602466,277.855991