In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/workspaces/steel_stock_management/data/inventory_df.csv')
df.set_index('fecha')

                                     material  inventario
fecha
2026-05-19                   ALAMBRE RECOCIDO     1924.63
2026-05-19                           ALAMBRON     1108.00
2026-05-19                   ARMEX DE 15 x 15      551.00
2026-05-19                   ARMEX DE 15 x 20        9.00
2026-05-19  CLAVO P/CONCRETO 2 1/2" GALV 1 KG      295.00
...                                       ...         ...
2026-06-25        CLAVO PARA MADERA DE 2 1/2"      180.20
2026-06-25            CLAVO PARA MADERA DE 4"      262.30
2026-06-25     MALLA ELECTROSOLDADA 6-6-10/10      701.80
2026-06-25             VARILLA CORRUGADA 1/2"      512.00
2026-06-25             VARILLA CORRUGADA 3/8"      645.00

[320 rows x 2 columns]

In [9]:
materials_df = pd.read_csv('/workspaces/steel_stock_management/data/mat_dict.csv')
mat_dict = materials_df.set_index("material").to_dict(orient="index")
mat_dict

{'ALAMBRE RECOCIDO': {'purchase_date': '2026-06-08',
  'received': '2026-06-12',
  'quantity': 500,
  'unit': 'kg',
  'minimum_stock': 1500},
 'ALAMBRON': {'purchase_date': '2026-06-08',
  'received': '2026-06-12',
  'quantity': 1000,
  'unit': 'kg',
  'minimum_stock': 1500},
 'ARMEX DE 15 x 15': {'purchase_date': '2026-04-17',
  'received': '2026-04-22',
  'quantity': 198,
  'unit': 'pzs',
  'minimum_stock': 132},
 'ARMEX DE 15 x 20': {'purchase_date': '2026-06-07',
  'received': '2026-06-12',
  'quantity': 144,
  'unit': 'pzs',
  'minimum_stock': 96},
 'CLAVO P/CONCRETO 2 1/2" GALV 1 KG': {'purchase_date': '2026-06-07',
  'received': '2026-06-22',
  'quantity': 250,
  'unit': 'kg',
  'minimum_stock': 100},
 'CLAVO PARA MADERA DE 2 1/2"': {'purchase_date': '2026-05-22',
  'received': '2026-05-26',
  'quantity': 200,
  'unit': 'kg',
  'minimum_stock': 100},
 'CLAVO PARA MADERA DE 4"': {'purchase_date': '2026-05-20',
  'received': '2026-05-26',
  'quantity': 100,
  'unit': 'kg',
  'minimum_stock': 100},
 'MALLA ELECTROSOLDADA 6-6-10/10': {'purchase_date': '2026-05-17',
  'received': '2026-05-13',
  'quantity': 1500,
  'unit': 'm²',
  'minimum_stock': 1000},
 'VARILLA CORRUGADA 1/2"': {'purchase_date': '2026-06-06',
  'received': '2026-06-18',
  'quantity': 504,
  'unit': 'pzs',
  'minimum_stock': 252},
 'VARILLA CORRUGADA 3/8"': {'purchase_date': '2026-05-21',
  'received': '2026-05-26',
  'quantity': 750,
  'unit': 'pzs',
  'minimum_stock': 600}}

In [10]:
df.describe(include='number').T

            count        mean          std  min    25%    50%     75%     max
inventario  320.0  954.792844  1125.730593  7.0  293.0  417.5  1439.5  6160.7